# Utilisation de l'image de base Python
FROM ghcr.io/mlflow/mlflow:latest

# Définition du répertoire de travail
WORKDIR /mlflow

# Installation des dépendances système
RUN apt-get update && apt-get install -y \
    build-essential \
    default-libmysqlclient-dev \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade pip

# Copie des fichiers requirements.txt dans le conteneur
COPY requirements_mlflow.txt .

# Installation des dépendances Python
RUN pip install --no-cache-dir -r requirements_mlflow.txt

# Copie des fichiers de l'application
COPY . .

# Exposition du port pour le serveur MLflow
EXPOSE 5000
